# A sample Gemfile
source "http://rubygems.org"

gem "rails",'2.3.8'
gem 'mysql2'
gem 'devise','1.0.8'

group :development do
  gem 'rspec-rails',      '=1.3.2', :require => false
end

group :test do
  gem 'rspec',            '=1.3.0', :require => false
  gem 'rspec-rails',      '=1.3.2', :require => false

  gem "shoulda", "2.10.3", :require => "shoulda"
  gem "factory_girl", "1.2.4", :require => "factory_girl"
  gem "faker", '0.3.1'
  gem 'fakeweb'
end





